# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '自定义collectionView移动带动画' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage', '~> 4.0.0'
 pod 'MJExtension', '~> 3.0.13'
  # Pods for 自定义collectionView移动带动画

  target '自定义collectionView移动带动画Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '自定义collectionView移动带动画UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
